apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udacity
  template:
    metadata:
      labels:
        app: udacity
    spec:
      containers:
      - name: udacityapp
        image: samargooda/udacity
